services:
  db:
    container_name: barbershop_container
    image: postgres
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: barbershop
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
